### ISSUE TITLE
RS232 connection for Cytomat

### ISSUE THREAD

**Issue by isaacguerreir** [stefangolas/olaf#1]
Hey Stefan,

I checked and it seems very compatible your code for the cytomat and the software specifications defined on the manual of the Cytomat I have here in Brazil.

The only interesting thing is the machine only communicate through a RS232 cable, so I'm wondering if I connect to my computer using a RS232-to-USB adapter it will work as expected.

Is that your experience or you writed this code for a Cytomat that have a USB connection?

**Comment by stefangolas** [comment]
You don't need to use an adapter, just connect from your computer to the Cytomat and it will work fine.
